apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec: 
  capacity: 
    storage: 1Gi 
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
    # - ReadOnlyMany not available for local
    # - ReadWriteMany not available for local
  hostPath:
    path: /data
    type: DirectoryOrCreate